exports.seed = function(knex, Promise) {
  return knex('recipe').del()
    .then(function () {
      return knex('recipe').insert([
        {id: 1, name: 'Pan-Roasted Pork Chops with ', cooking_duration:'35',description:'Tuna steaks always feel like a treat, something you save for a special occasion, but we don’t see any reason why that has to be the case. Our wild-caught tuna is joined by seasonal heirloom zucchini, sliced into delicate ribbons and sprinkled with fresh mint and zested lemon. With nutty farro and perfectly seared tuna that is pink on the inside and crusted with crunchy pink peppercorns on the outside, you may just forget that you’re sitting at your kitchen table and not at a gourmet farm-to-table bistro.',category_id:'3'},
        {id: 2, name: 'Vietnamese Grilled Chicken Thighs', cooking_duration:'20',description:'In the mood for a Vietnamese-inspired plate? Look no further than this quick-to-make recipe, which sees chicken thighs grilled to perfection before being brushed with a mouthwatering chili sauce. We serve ‘em up on a bed of delicate rice vermicelli alongside pickled vegetables: spiralized daikon and carrots and thin slices of cucumber are all marinated in garlic and rice vinegar to make a delightfully tangy side. A sprinkle of fresh cilantro makes for a fragrant finish. Nothing left to do but dig in!',category_id:'4'},
        {id: 3, name: 'Madras Tofu-Mango Curry', cooking_duration:'35',description:'Sugar and spice and everything nice! Madras is typically a mouth-on-fire kind of curry sauce, but this mild vegetarian version keeps the layered flavour profile of this classic curry without the sensory assault of chili. Plenty of fresh ginger, lime zest and a spice blend made with fragrant turmeric, mustard seeds and garlic add tang and complexity to the dish, while creamy coconut milk brings out the sweetness in the chunks of mango and starchy sweet potatoes. Finish it off with a hearty helping of kale, good squeeze of lime and a sprinkle of fresh mint for a zip of brightness and you’ve got your new favourite meatless dinner!',category_id:'1'},
        {id: 4, name: 'Spiced Cod with Braised Chickpeas & Cherry Tomatoes ', cooking_duration:'60',description:'Our signature roasted garlic & red pepper spice blend takes centre stage tonight. We make use of the garlic, bell pepper, paprika and turmeric combo to season both the fillets of cod and our sides. First we brown plump cherry tomatoes in the pan, then stir in our chickpeas and seasoning. After braising the legumes, we add in the seasoned fish to cook. A light spinach salad is whipped up with a drizzle of olive oil and a splash of sherry vinegar. With that, your fragrant, fast-to-make dish is ready to savour!',category_id:'5'},
        {id: 5, name: 'Greek Beef Burgers with Tzatziki', cooking_duration:'40',description:'There’s something about a burger that’s just so craveworthy on a warm early summer evening. Do the art of burger-making (and eating!) justice with this souvlaki-inspired take on the American barbecue classic. We mix ground beef with onions and our Greek spice blend for juicy, flavour-packed patties that recall the flavours of the Mediterranean. Dollops of tzatziki and crunchy cucumbers join your classic fixings and oven-roasted wedge fries to usher in a BBQ season of better burgers.',category_id:'3'},
        {id: 6, name: 'Turkish Chicken Kebabs with Garlic Yogurt', cooking_duration:'30',description:'You might be most familiar with kebabs from late night, neon-lit shops, but this quintessential Turkish street food is not just fit for take-out. Chargrilled to smoky perfection, juicy and tender chicken kebabs soak up tons of flavour from a cool and bright tzatziki-esque sauce with a little added flair by way of lemon zest. Our absolute favourite bit here, though, are the crunchy spiced cucumbers! Red cabbage adds a pop of colour, and olive oil-drizzled couscous is a light and fluffy accompaniment.',category_id:'4'},
        {id: 7, name: 'Grilled Lamb Chops', cooking_duration:'35',description:'Ladolemono, a super-simple sauce made from fresh lemon and olive oil, is a hallmark of traditional Greek cuisine most often poured over fish to give it extra juicy brightness. There’s nothing to say, however, that it can’t work just as well on robust, earthy lamb chops and bittersweet broccolini. Greek cuisine is also big on rice, so we’ve paired the tender meat and greens with a nutty red rice pilaf, livened up with roasted red pepper, mint, and a little extra lemon zest. Go ahead and spoon a little ladolemono over that too.',category_id:'2'},
        {id: 8, name: 'Haddock & Spinach-Farro Salad', cooking_duration:'40',description:'Boasting a serious amount of vitamins and protein, farro should be a staple of every vegetarian’s pantry. We love featuring the grain in warm salads; its naturally nutty flavour is only enhanced by tangy vinaigrette and a medley of seasonal vegetables. We have paired it with spinach and radish and drizzled everything with a date, shallot and champagne vinegar dressing for a light and elegant result. Delicious haddock fillets complete this spectacular meal whose flavours and texture will undoubtedly satisfy all your dinner guests!',category_id:'4'},
        {id: 9, name: 'Grilled Tofu with Fresh Chimichurri', cooking_duration:'20',description:'Who said BBQ season was reserved for meat lovers? Not us, that’s for sure! We whip up a fresh chimichurri by combining fragrant parsley, cilantro and mint with lime juice, a splash of red wine vinegar and a drizzle of olive oil; use it to add flavour and colour to slices of tofu that have been grilled to perfection. Multicoloured baby peppers join the tofu on the grill until they, too, are browned and tender. Serve up this dish with a side of roasted butternut squash and ginger for a meal that is guaranteed to please vegetarians and omnivores alike!',category_id:'1'}
      ]);
    });
};
